# Generated by Django 3.2.8 on 2021-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_age', models.IntegerField()),
                ('artist_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
