# Generated by Django 3.2.8 on 2021-10-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_regNo', models.TextField(unique=True)),
                ('employee_name', models.TextField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_modile', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
